### ISSUE TITLE
[Feature Request] Sign message

### ISSUE THREAD

**Issue by ghost** [PIVX-Project/PIVX-SPMT#11]
Please add "Sign Message" function. Thank You @random-zebra

**Comment by random-zebra** [comment]
Sure.
You mean sign an arbitrary text message with the key to the collateral address of a masternode (for example, to provide a "proof of ownership")?

**Comment by ghost** [comment]
> collateral address

Yes, all of you truly understood. But only to have an opportunity to sign the message for any address which is on Ledger, not only the deposit address.

**Comment by random-zebra** [comment]
Alright. I see there's a feature request to add this capability to Ledger live (https://github.com/LedgerHQ/ledger-live-desktop/issues/1136), as it was present on the Chrome Wallet App. 
I will add it in the near future if the issue isn't resolved.

**Comment by random-zebra** [comment]
Feature merged in master. Available running from sources (`python spmt.py`).
New binary release will be out soon.
