### ISSUE TITLE
Application crashes

### ISSUE THREAD

**Issue by ghost** [PIVX-Project/PIVX-SPMT#12]
Hi @random-zebra 
When I send Collateral to any addres^ Application crashes.
I wanted to transfer coins to a new address.

macOS Mojave 10.14.5

**Comment by random-zebra** [comment]
Hi @ElvisPresly .
This is most probably related to https://github.com/PIVX-Project/PIVX-SPMT/pull/8 which is fixed in next version (v0.5.0).

You can download the pre-release version here: https://github.com/random-zebra/SPMT/releases/tag/v0.5.0-alpha.3

**Comment by random-zebra** [comment]
v0.5.0 released
