### ISSUE TITLE
Last version not start

### ISSUE THREAD

**Issue by ghost** [PIVX-Project/PIVX-SPMT#32]
latest version does not start on Macos Catalina 10.15.3
The application blinks quickly once and nothing happens.

**Comment by random-zebra** [comment]
@ElvisPresly with which file does this happen? `dmg` app bundle, or the `tar.gz` archive?
Have you tried launching it from the command line with the `--clearAppData` flag?

**Comment by ghost** [comment]
@random-zebra 
dmg
--clearAppData - did not try, it will not delete my settings?

**Comment by random-zebra** [comment]
No `--clearAppData` only resets qt specific settings. Your MNs and remote servers configuration is retained. 
Anyways, no need to: this seems to be related to something else (specifically for the dmg file). 
Could you please try the `tar.gz` file instead?

**Comment by ghost** [comment]
@random-zebra 
tar.gz - it works thanks

**Comment by random-zebra** [comment]
Thanks for the notification. We'll fix up the issue with the dmg.
Closing.
