### ISSUE TITLE
Masternode not founded

### ISSUE THREAD

**Issue by othe-alchemist** [PIVX-Project/PIVX-SPMT#37]
Hi everybody,
I try to enable a masternode on a Home Ubuntu Server.
SPMT v.0.6.1-a
PIVX-Qt: v4.1
Ubuntu: 18-04
Ledger nano S

I have followed the indications : https://github.com/PIVX-Project/PIVX-SPMT
Everything seem to be good. Then i start my masternode and get status ACTIVE (when click on "Get Status of all Masternodes").
But after 2 long hours, nothing happen and when i click on "Get Status of all Masternodes", i get : "Masternode not founded".

I set-up a Local Wallet and i get the pink light in SPMT at the line PIVX RPC Server.
Seem to be ok !

Here is my pivx.conf file : 

rpcuser=i put a long one
rpcpassword=i put a longer one
rpcallowip=127.0.0.1
server=1
daemon=1
listen=1
logtimestamps=1
maxconnections=256
masternode=1
externalip=<even if some day my ext IP change (Home Box), i put the right one>
masternodeaddr=<I put the same as above>:51472
masternodeprivkey=<I put the privkey generated in SPMT>

Any Help ?

**Comment by random-zebra** [comment]
Hi. Your masternode (remote server) needs a public IP address and the IP port open and forwarded to your machine. 

Please join Discord community at https://discordapp.com/invite/jzqVsJd if you need support. This tracker here is just for bug/issue-reports and feature requests. Closing.
