### ISSUE TITLE
Masternode isn't starteable with new Pivx 5.0 version

### ISSUE THREAD

**Issue by Jumperbillijumper** [PIVX-Project/PIVX-SPMT#41]
With old SPMT version it is not possible to start a new Pivx 5.0 Masternode.

![SPMT](https://user-images.githubusercontent.com/22638600/104227906-61cbee80-544a-11eb-9c23-9748f46a6fa5.PNG)
![VPS](https://user-images.githubusercontent.com/22638600/104227907-61cbee80-544a-11eb-9813-9a013744b99f.PNG)

**Comment by random-zebra** [comment]
The remote RPC server needs to be updated to PIVX version 5.0 as well (if you are using a local node).

If, instead, you are using the public "randomzebra.party" servers, consider that:
- amsterdam is upgraded to v5.0 already
- losangeles is still running v4.3

**Comment by Jumperbillijumper** [comment]
Ah, thanks! That was easy :)
