### ISSUE TITLE
Can't connect trezor one

### ISSUE THREAD

**Issue by chilly2k** [PIVX-Project/PIVX-SPMT#45]
I've been using SPMT for a few years to mange a masternode with my trezor.  Just tried to open it to sweep rewards and when I try to connect with the trezor, I get data error: invalid coin name.   Last time I used it was up to 2 months ago.   Since that time I have increased ram, and installed a new SSD as my c drive.  I cloned the original drive, and swapped them.  
   Once the failure started I Tried rolling the trezor firmware back to 1.10.0 level and changing SPMT to start from the E: drive (original C: drive.

**Comment by Bleujj1** [comment]
You willl have to upgrade your device , synchronize it and then you debug it

**Comment by Bleujj1** [comment]
You willl have to upgrade your device , synchronize it and then you debug it

**Comment by chilly2k** [comment]
Reloaded the 1.10.5 firmware.  Restarted SPMT.  It finds the Trezor and reports level 1.10.5, and then  
2022-02-23 18:46:07 : Initializing Trezor
===> Trezor HW device connected [v. 1.10.5]
2022-02-23 18:46:08 : Current version is (1, 10, 5) (minimum required: (1, 8, 0))
EXCEPTION
caller : updateHWstatus
function : initDevice
err: DataError: Invalid coin name
===> Trezor Exception
2022-02-23 18:46:29 : Closing TREZOR client
2022-02-23 18:46:29 : DataError: Invalid coin name
2022-02-23 18:46:29 : status:0 - mess: Not Connected

**Comment by Bleujj1** [comment]
You will have to synchronize your wallet and then you debug it

**Comment by chilly2k** [comment]
Not sure what you mean synchronize my wallet.  I wasn't using a local wallet.  (I have and can do that, but I did not for this test).  I'm sure your talking about something with the trezor wallet, but I've never heard of syncing that.

**Comment by chilly2k** [comment]
I tried installing SPMT on another laptop and get the same problem.  I even wiped the trezor and reinstalled, same problem.  I'm wondering if something changed in the trezor libraries.

**Comment by chilly2k** [comment]
Could this be the answer? https://github.com/trezor/trezor-firmware/issues/1358   Looks like trezor removed pivx as a supported coin in Nov 2020.  Somehow that got rolled into my system (I'm guessing).  Do we need to put in a new request to Trezor to include PIVX support?

**Comment by random-zebra** [comment]
Hi @chilly2k.
Yes, unfortunately Trezor removed PIVX in version [1.9.4](https://github.com/trezor/trezor-firmware/blob/dd1240ef530eed549d90b1beea371a318c208350/core/CHANGELOG.md) of the firmware of Trezor One (version 2.3.5 for model T), due to the lack of wallets supporting it (and SPMT not being classified as a wallet).

You will have to [downgrade](https://wiki.trezor.io/Firmware_downgrade) the firmware of your device to a previous version.
Alternatively, you can extract the private key from the mnemonic with a bip39 tool (such as https://github.com/iancoleman/bip39), import it into a PIVX core wallet (with the command `importprivkey`), and then spend your coins from the PIVX wallet.

**Comment by chilly2k** [comment]
Zebra, Thanks,  I was able to use the tool and move the key to my wallet.  Should I pursue with Trezor to get pivx added back in, or is that off the table.  I liked using SPMT to mange the masternode.  

      Thanks

**Comment by random-zebra** [comment]
It might be worth trying. I think that they could consider adding it back if they receive enough requests (possibly explaining that SPMT covers this specific use case for the device, even though it's not a full-fledged wallet).
