### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ghost** [PIVX-Project/PIVX-SPMT#46]
1) Not connetction to servers
2) Not connection to Ledger Nano X (Pivix last app)
<img width="992" alt="Снимок экрана 2022-04-29 в 11 31 23" src="https://user-images.githubusercontent.com/18265958/165910977-ce87463a-4492-4742-aa11-91bb43b98eb4.png">

**Comment by ghost** [comment]
solution
https://github.com/Bertrand256/dash-masternode-tool/issues/45

**Comment by Fuzzbawls** [comment]
#47 should fix the hardware connection for Ledger devices running newer app versions.

working on a separate PR to migrate to some new public RPC servers

**Comment by ghost** [comment]
> #47 should fix the hardware connection for Ledger devices running newer app versions.
> 
> working on a separate PR to migrate to some new public RPC servers

RPC is still unavailable, I already regret that I decided to support this coin. I can't even get coins from the masternodes

**Comment by Fuzzbawls** [comment]
v0.6.3a has been released, fixing both issues. You've always had the option to use your own RPC server as a fallback, however.

**Comment by ghost** [comment]
hello, not running
<img width="307" alt="Снимок экрана 2022-06-22 в 09 30 57" src="https://user-images.githubusercontent.com/18265958/174959191-ab970731-557f-4531-9474-d061e2d53c54.png">

**Comment by ghost** [comment]
@Fuzzbawls up

**Comment by Fuzzbawls** [comment]
> hello, not running <img alt="Снимок экрана 2022-06-22 в 09 30 57" width="307" src="https://user-images.githubusercontent.com/18265958/174959191-ab970731-557f-4531-9474-d061e2d53c54.png">

I can't read that

**Comment by ghost** [comment]
> > hello, not running <img alt="Снимок экрана 2022-06-22 в 09 30 57" width="307" src="https://user-images.githubusercontent.com/18265958/174959191-ab970731-557f-4531-9474-d061e2d53c54.png">
> 
> I can't read that

Application quit unexpectedly

**Comment by Fuzzbawls** [comment]
can you please paste the contents of any "Crash Report" (in english) here? I did notice from your first screenshot that you're running macOS Monterey on a 2017 mac, which should be an intel chip. I'm not able to do direct troubleshooting on macOS Monterey with intel chips as my intel-based mac is too old to run that OS version

**Comment by ghost** [comment]
> can you please paste the contents of any "Crash Report" (in english) here? I did notice from your first screenshot that you're running macOS Monterey on a 2017 mac, which should be an intel chip. I'm not able to do direct troubleshooting on macOS Monterey with intel chips as my intel-based mac is too old to run that OS version

ok
[Report.txt](https://github.com/PIVX-Project/PIVX-SPMT/files/8956200/Report.txt)

**Comment by Fuzzbawls** [comment]
ok, seems that for some reason newer versions of macOS are saying that the code signature is invalid:
```
EXC_BAD_ACCESS (SIGKILL (Code Signature Invalid))
```

I've no clue why this is happening since the certificate we use for code signing was issued in 2020 and is valid until 2025.

will need to do some investigation.

**Comment by Fuzzbawls** [comment]
Can you try this file?
https://drive.google.com/file/d/17il9pFknR_tTpm9joXtkVC3xzLIqf6z1/view?usp=sharing

if it works then i'll update the file on the release page. if it doesn't, please send the crash report again

**Comment by ghost** [comment]
> Can you try this file? https://drive.google.com/file/d/17il9pFknR_tTpm9joXtkVC3xzLIqf6z1/view?usp=sharing
> 
> if it works then i'll update the file on the release page. if it doesn't, please send the crash report again

CPU usage is 100% and the program won't start
<img width="343" alt="Снимок экрана 2022-06-28 в 09 07 45" src="https://user-images.githubusercontent.com/18265958/176105648-34cb889c-e087-4bd2-a3c5-7f2182eebc97.png">

**Comment by Fuzzbawls** [comment]
ok, more digging it is then. will see about getting an intel app built on my macOS Big Sur M1 machine.

in the mean time, you could **maybe** get the app working by running it natively in python:
1. If you don't already have homebrew installed, install it from the terminal app with
```zsh
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```
2. install python 3.7 from the terminal with
```zsh
brew install python@3.7
```
3. clone the PIVX-SPMT repository with
```zsh
cd $HOME && git clone https://github.com/PIVX-Project/PIVX-SPMT.git && cd PIVX-SPMT
```
4. setup a python3 virtual environment for SPMT with
```zsh
/usr/local/opt/python@3.7/bin/python3 -m venv venv37
```
5. activate the newly created virtual environment. NOTE: after this, your terminal line should start with `(venv37)` at the very beginning.
```zsh
source venv37/bin/activate
```
6. now install the necessary python requirements with
```bash
pip install -r requirements.txt
```
7 run the app with
```bash
python3 spmt.py
```

**Comment by ghost** [comment]
> ok, more digging it is then. will see about getting an intel app built on my macOS Big Sur M1 machine.
> 
> in the mean time, you could **maybe** get the app working by running it natively in python:
> 
> 1. If you don't already have homebrew installed, install it from the terminal app with
> 
> ```shell
> /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
> ```
> 
>  2. install python 3.7 from the terminal with
> 
> ```shell
> brew install python@3.7
> ```
> 
>  3. clone the PIVX-SPMT repository with
> 
> ```shell
> cd $HOME && git clone https://github.com/PIVX-Project/PIVX-SPMT.git && cd PIVX-SPMT
> ```
> 
>  4. setup a python3 virtual environment for SPMT with
> 
> ```shell
> /usr/local/opt/python@3.7/bin/python3 -m venv venv37
> ```
> 
>  5. activate the newly created virtual environment. NOTE: after this, your terminal line should start with `(venv37)` at the very beginning.
> 
> ```shell
> source venv37/bin/activate
> ```
> 
>  6. now install the necessary python requirements with
> 
> ```shell
> pip install -r requirements.txt
> ```
> 
> 7 run the app with
> 
> ```shell
> python3 spmt.py
> ```

it's too hard for me :(

**Comment by Fuzzbawls** [comment]
ok, try this one:
https://drive.google.com/file/d/1dbGeXVjVHJuKJWGcSjYx2-_6gAdlRzG8/view?usp=sharing

was built on macOS Big Sur on a M1 chip using Rosetta2 to get an intel app instead of an apple silicon app.

**Comment by ghost** [comment]
> ok, try this one: https://drive.google.com/file/d/1dbGeXVjVHJuKJWGcSjYx2-_6gAdlRzG8/view?usp=sharing
> 
> was built on macOS Big Sur on a M1 chip using Rosetta2 to get an intel app instead of an apple silicon app.

its working, thank you

**Comment by Fuzzbawls** [comment]
ok cool. i'll update the official release binaries this week. You can use the one above in the mean time. have noted that moving forward, we will need to have two separate sets of macOS downloads (one for 10.13-10.15, and another for 11+)

**Comment by Fuzzbawls** [comment]
ok, have updated the binaries on the official release page (along with new SHASUMS) for both SPMT and PET4L. You should download the `.dmg` file that has `MacOS-11-plus` in the file name
