### ISSUE TITLE
SPMT 0.4.1 does not start on linux

### ISSUE THREAD

**Issue by TheSaltyJ** [PIVX-Project/PIVX-SPMT#6]
Hello

I updated to 0.4.1 but the app won't launch on my Ubuntu 18.04.1. The loading screen appears but afterwards the app does not launch. I also do not see any PID running.

Best,
TheSaltyJ

**Comment by random-zebra** [comment]
@TheSaltyJ could you please try to launch it from the command line and tell me if you get any exception?
```
cd SPMT-v0.4.1a-gnu_linux/app
./SecurePivxMasternodeTool
```
Are you updating from 0.4.0 or from a previous version?

**Comment by TheSaltyJ** [comment]
Hey random-zebra
Sorry for the late answer. I update from 0.4.0 I tried your approach and I receive the following:

./SecurePivxMasternodeTool
<b style="color: yellow">2018-12-21 12:17:41</b> : trying to open database...<br>
<b style="color: yellow">2018-12-21 12:17:41</b> : Database open<br>
<b style="color: yellow">2018-12-21 12:17:41</b> : Creating HW device class<br>
QThread: Destroyed while thread is still running
Bus error (core dumped)

I hope this helps.

**Comment by random-zebra** [comment]
Thanks. It will be fixed in next release.
As a temporary workaround, try launching from the terminal with the `clearAppData` flag:
```
./SecurePivxMasternodeTool --clearAppData
```

**Comment by TheSaltyJ** [comment]
It worked :)
